# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET https://localhost:7162/terje

###

POST https://localhost:7162/terje
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
    "text": "Terje"   
}